# DENNE ER generert med GPT. Ikke testet.

name: Update requirements and build

on:
  push:
    branches:
      - main

jobs:
  update_and_build:
    runs-on: ubuntu-latest

    steps:
    # Sjekk ut koden fra repoet
    - name: Checkout code
      uses: actions/checkout@v3

    # Sett opp Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Installer avhengigheter
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools build

    # Installer prosjektavhengigheter
    - name: Install project dependencies
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi

    # Oppdater requirements.txt med pip freeze
    - name: Update requirements.txt
      run: |
        pip freeze > requirements.txt
      shell: bash

    # Bygg prosjektet
    - name: Build the project
      run: |
        python -m build

    # Commit og push endringer
    - name: Commit and push changes
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add requirements.txt
        git commit -m "Update requirements.txt [skip ci]" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}